### ISSUE TITLE
Moffat Bible online in an obscure website

### ISSUE THREAD

**Issue by DavidHaslam** [ThomHehl/Moffatt#5]
I just went looking for the [Ferrar Fenton Bible](https://en.wikipedia.org/wiki/Ferrar_Fenton_Bible) translation. _Had you heard of that?_

An external link therein took me to [here](http://bazinta.com/index.php?t=MFT) in which I just selected the Moffat translation. It's _only_ the **New Testament** with this selection.

btw. The webmaster has slapped a copyright notice on everything hosted, which reads:
> Copyright © 2014 This content is protected by copyright and may not be converted or disseminated in any form without written permission. 

NB. I don't think this is a valid claim in legal terms for those translations that have passed into the public domain. However, I should note that I am not a copyright lawyer. One thing is pretty certain. File format shifting by making digital copy of a printed work does not create a new work with its own copyright.

**Comment by ThomHehl** [comment]
I had found that, yes. I was relieved that I could just grab the New Testament from there.

Yeah, you can't retroactively copywrite something in the public domain.
