### ISSUE TITLE
Incorrect poetry tags in 1 Chronicles

### ISSUE THREAD

**Issue by DavidHaslam** [ThomHehl/Moffatt#6]
Poetry tags are wrong.  There's no marker called `\qt1`.

Poetry tags are like paragraph tags. No end tag is needed.

Please read the **USFM User Reference** and use the proper poetry markers.

- Always remember the correct syntax for USFM tags.
- The **underscore** in the documentation signifies a **required space**.

Thus, using level 1 poetry tags, you should have:
```
\v 18 Amasa, who was commander-in-chief, was inspired to reply,
\q1 We are your men, David,
\q1 on your side, O son of Jesse!
\q1 Peace, peace to you,
\q1 and to your helpers peace--
\q1 for your God helps you!
\p Then David admitted them and made them captains of his band.
```
The paragraph tag ends the poetry lines.

**Comment by ThomHehl** [comment]
Oh, dear, I was combining the quoted text and the poetry tags.

So it looks like the quotes don't have a level. How do I handle a quote in a quote? The example uses a single quote inline.

Thanks so much for your help!

**Comment by DavidHaslam** [comment]
It's not a case of quote within a quote. Rather it's a quotation that is also poetry (of sorts).
_Try this as an improvement._ 
```
\p \v 18 Amasa, who was commander-in-chief, was inspired to reply,
\q1 \qt We are your men, David,\qt*
\q2 \qt on your side, O son of Jesse!\qt*
\q1 \qt Peace, peace to you,\qt*
\q2 \qt and to your helpers peace―\qt*
\q2 \qt for your God helps you!\qt*
\p Then David admitted them and made them captains of his band.
```
Note that I also made 3 lines as level 2 poetry using `\q2 ` in place of `\q1 `.

btw. I also replaced the `--` by a horizontal bar, U+2015. It's displayed length will be font-dependent.

I assumed that v18 is the start of a new paragraph, without checking back.

**Comment by DavidHaslam** [comment]
Quoted text is a special character style, so it has a start and end tag.

Poetry tags are classed with paragraph tags. They don't have an end tag.

**Comment by DavidHaslam** [comment]
If you need to make use of non-ANSI characters, suggest download and install the excellent Unicode text editor called [BabelPad](http://www.babelstone.co.uk/software/babelpad.html).

**Comment by ThomHehl** [comment]
@DavidHaslam Wow! Thanks again for the save.

Since there are no quotations in the original text and only one level of indent, and no paragraphs anywhere around verse 18, I used this:

\v 18 Amasa, who was commander-in-chief, was inspired to reply,
\q1 We are your men, David,
\q1 on your side, O son of Jesse!
\q1 Peace, peace to you,
\q1 and to your helpers peace--
\q1 for your God helps you!
Then David admitted them and made them captains of his band.

**Comment by ThomHehl** [comment]
@DavidHaslam the quotations I was discussing are from 11:1-2:

\c 11
\p
\v 1 Then all Israel gathered round David at Hebron, saying, \qt Here we are, your own bone and flesh!
\v 2 In bygone days, even when Saul was our king, it was you who led Israel out and in; the Eternal your God said to you, \qt You shall shepherd my people Israel, you shall be prince over my people Israel!\qt*\qt*

**Comment by DavidHaslam** [comment]
You need a paragraph tag before 
Then David ...

Otherwise it's counted as part of the last poetry line.

**Comment by ThomHehl** [comment]
Like this:
\v 18 Amasa, who was commander-in-chief, was inspired to reply,
\q1 We are your men, David,
\q1 on your side, O son of Jesse!
\q1 Peace, peace to you,
\q1 and to your helpers peace--
\q1 for your God helps you!
\p Then David admitted them and made them captains of his band.

**Comment by DavidHaslam** [comment]
Yes.

I've not looked at this passage in the printed edition,
so I've not checked to see of any poetry lines have a larger indent than others.

Here's an "Aha!" insight about USFM.

ParaTExt treats an end of line more or less like a space.  The EOLs are not really that significant. 

It expects certain tags to be at the start of a line, but that's more an internal requirement. 

Not sure how Bibledit fares in this respect.

In adyeths/u2o.py script, the first thing he does is to linearise each input USFM file.

**Comment by DavidHaslam** [comment]
If Moffatt has a horizontal line rather than two hyphens, try to match him accurately.

**Comment by ThomHehl** [comment]
My OCR software scans the em dash inconsistently, so I decided to simply use -- to replace them. I think I agree with you, though, that I should use a proper em dash, but, when I made that decision, I knew it would be easy enough to do a search and replace later and that's probably what I'll end up doing.

Thanks again for the assist.

**Comment by DavidHaslam** [comment]
Referring to your observation about the other passage:
```
\c 11
\p
\v 1 Then all Israel gathered round David at Hebron, saying, \qt Here we are, your own bone and flesh!
\v 2 In bygone days, even when Saul was our king, it was you who led Israel out and in; the Eternal your God said to you, \qt You shall shepherd my people Israel, you shall be prince over my people Israel!\qt*\qt*
```
I don't think quoted text within quoted text like this would work.

You should use the **nested syntax** for character level USFM tags.
```
\c 11
\p
\v 1 Then all Israel gathered round David at Hebron, saying, \qt Here we are, your own bone and flesh!
\v 2 In bygone days, even when Saul was our king, it was you who led Israel out and in; the Eternal your God said to you, \+qt You shall shepherd my people Israel, you shall be prince over my people Israel!\+qt*\qt*
```

This is a very interesting case. Worth looking to see how `u2o.py` handles it.

NB. I've not discussed this with any of my expert **ParaTExt** friends.

**Comment by DavidHaslam** [comment]
Upon further thought, I think there's some _confusion_ here.

This passage in chapter 11 is **not** an example of quoted text within quoted text.
It is merely an example of a **speech** that _includes_ some **quoted text**.

I expect this analysis will be confirmed when my friend replies.

The outer tags are therefore not required. The inner tags need not use nested syntax.

Unless, of course, a different pair of tags is used to wrap the speech.
Modern translations simply use quotation marks for that purpose.
There's no special tags for speech _per se_, apart from the **\wj_...\wj*** markers used for the **Words of Jesus** (which facilitates red letter editions).

**Comment by ThomHehl** [comment]
Would you be so kind as to mention that to them, @DavidHaslam. I will let you know how it turns out from u20.py.

**Comment by DavidHaslam** [comment]
I will await his reply.

**Comment by DavidHaslam** [comment]
I've had a holding message reply, so I sent him my later analysis.

The important thing to understand is that quoted text always quotes text from someone or something else.

Most speech is not quoted text.

The confusion arises because we often call speech marks quotation marks.

In fact, the name of each of Unicode characters is ...... QUOTATION MARK.

**Comment by DavidHaslam** [comment]
My friend replied as follows:

> The label `\qt` is used for quoting a section or verse of Scripture from elsewhere.  Usually in the stylesheet it will be marked to be italicised.  It is closed with a `\qt*`  
> It has be closed and re-opened at each new verse marker e.g.   `\qt …. \qt* \v 1 \qt ……. \qt*`
> 
> At the end of a \qt* I would usually expect a `\x …. \x*` cross-reference note telling me where it is quoted from.
> I cannot think of a case in the Bible where we need to do **nested** `\qt` i.e. `\qt …. \+qt ….\+qt*… \qt*` and I do not think this is one of those cases.  Just quoting someone’s speech is not the same as a quotation from elsewhere.
> 
> So if you are digitising an old text that did not use `“….”`  then I would not expect you to need to use `\qt … \qt*` where today you would put `“…”`. 
> 
> So in the **King James** for **2 Samuel 5:1-2** we have simply:
```
\v 1 Then came all the tribes of Israel to David unto Hebron, and spake, saying, Behold, we \add are\add* thy bone and thy flesh. \v 2 Also in time past, when Saul was king over us, thou wast he that leddest out and broughtest in Israel: and the \nd LORD\nd* said to thee, Thou shalt feed my people Israel, and thou shalt be a captain over Israel.
```
> and in the parallel verse in **1 Chronicles 11:1-2**
```
\p \v 1 Then all Israel gathered themselves to David unto Hebron, saying, Behold, we \add are\add* thy bone and thy flesh. \v 2 And moreover in time past, even when Saul was king, thou \add wast\add* he that leddest out and broughtest in Israel: and the \nd LORD\nd* thy God said unto thee, Thou shalt feed my people Israel, and thou shalt be ruler over my people Israel.
``` 
> _Without seeing what you are digitising it is hard to know what you want to do.  Is part of this verse indented or italicised in the original which you need to mark up?  If there is nothing which needs to be marked up then it looks to me like you do not need to use `\qt ` at all in these lines._
